### PR TITLE
Quiet tests

### PR DESCRIPTION
**Pull request by mcr**
the tests still throw many warnings, should run with -Werror
this helps get there.

### CODE REVIEW

**Comment by mcr** [comment]
sorry, this repeats part of a previous pull request, and I can't make it smaller yet.

**Comment by laurencelundblade** [comment]
So thanks for this. Will work through it.

I intentionally do not have warnings on so that by default it will compile without warning for most people. Easy install and set up is important. So I don't want to have warnings on in the main build. 

But before I merge anything to master I compile with the warnings on with llvm and gcc so that even if you turn them on, it should compile cleanly. From some of the errors you have fixed, it seems maybe my script is not working right. 

The script I use before merge is here: https://github.com/laurencelundblade/qdv. It fans out all combos of #ifdef and takes a while to run.

**Comment by laurencelundblade** [comment]
I've created #84 as an alternative to this PR. It addresses most of this. I did this separate because some of the fixes where a little different and I don't want to set -Wbad-function-cast because the fixes for it create warnings when using other compilers. Will add the CI enabling change in a separated PR.

I'm going to let this PR set for a few days before merging.

Thanks very much for this. It was helpful.

**Comment by laurencelundblade** [comment]
This was largely addressed by #84. -Wbad-function-cast was not addressed because fixes for it create other warnings with other compilers.

Thanks in general for the help!

**Pull request closed without merging**
